import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer & Assistant Coordinator',
    company: 'GEIP EdTech Project',
    company_legal_name: 'Faculty of Education (MoEYS), Cambodia',
    logo: '/images/careers/moeys.png',
    location: 'Phnom Penh, Cambodia 🇰🇭',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2023-09',
    end_date: null,
    industry: 'edtech',
    link: 'https://geip.edu.kh',
    responsibilities: [
      'Led the end-to-end development and maintenance of the GEIP EdTech App, a digital learning platform for self-study, reaching over 400,000 users and serving 20,000 daily active students across 1,861 schools.',
      'Architected and implemented features using Dart, Flutter, Firebase, PHP, Next.js, and Laravel to support a personalized and gamified learning experience.',
      'Acted as a Mobile App Teacher for React Native, training junior developers and creating educational materials.',
      'Developed a full-stack e-commerce project for training purposes using AWS Amplify, React Native, S3, and Redux.',
      'Built digital worksheets for all subjects, adaptive learning systems, PISA-aligned assessment systems, student analytics, and gamification with AI tools.',
    ],
  },
  {
    position: 'Full-Stack Developer',
    company: 'Zando Co., Ltd',
    company_legal_name: 'Zando Co., Ltd',
    logo: '/images/careers/zando.png',
    location: 'Phnom Penh, Cambodia 🇰🇭',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2022-03',
    end_date: '2022-12',
    industry: 'ecommerce',
    link: 'https://zando.com.kh',
    responsibilities: [
      'Developed a feature-rich e-commerce mobile application from concept to deployment.',
      'Implemented new functionalities and maintained the existing codebase using React and other standard tools in the React ecosystem.',
      'Ensured high performance and a seamless user experience across the platform.',
      'Collaborated with cross-functional teams to deliver quality products on time.',
    ],
  },
  {
    position: 'Full-Stack Developer (Internship)',
    company: 'Paylessgate',
    company_legal_name: 'Paylessgate Japan',
    logo: '/images/careers/paylessgate.png',
    location: 'Tokyo, Japan 🇯🇵 (Remote)',
    location_type: 'Remote',
    type: 'Internship',
    start_date: '2019-09',
    end_date: '2023-05',
    industry: 'fintech',
    link: 'https://paylessgate.jp',
    responsibilities: [
      'Contributed to the development of a Wireless Train Scanner Mobile App intended to replace physical train cards.',
      'Built the frontend of the Student Feedback System Platform using Next.js.',
      'Integrated frontend with a robust backend powered by PHP Laravel.',
      'Gained experience in a cross-cultural team environment, participating in UI/UX design and agile development cycles.',
      'Worked with technologies including React.js, Next.js, PHP Laravel, Kotlin, Android SDK, Git, and Docker.',
    ],
  },
];
